<?php
//Variables for date and time
$day['en'][0] = "Monday";
$day['en'][1] = "Tuesday";
$day['en'][2] = "Wednesday";
$day['en'][3] = "Thursday";
$day['en'][4] = "Friday";
$day['en'][5] = "Sunday";
$day['en'][6] = "Saturday";
/* ... */
$day['es'][0] = "Lunes";
$day['es'][1] = "Martes";
$day['es'][2] = "Miércoles";
$day['es'][3] = "Jueves";
$day['es'][4] = "Viernes";
$day['es'][5] = "Sábado";
$day['es'][6] = "Domingo";
/* ... */
$day['cat'][0] = "Dilluns";
$day['cat'][1] = "Dimarts";
$day['cat'][2] = "Dimecres";
$day['cat'][3] = "Dijous";
$day['cat'][4] = "Divendres";
$day['cat'][5] = "Dissabte";
$day['cat'][6] = "Diumenge";
/* ... */
$day['en'][0] = "January";
$day['en'][1] = "February";
$day['en'][2] = "March";
$day['en'][3] = "April";
$day['en'][4] = "May";
$day['en'][5] = "June";
$day['en'][6] = "July";
$day['en'][7] = "August";
$day['en'][8] = "September";
$day['en'][9] = "October";
$day['en'][10] = "November";
$day['en'][11] = "December";
/* ... */
$day['es'][0] = "Enero";
$day['es'][1] = "Febrero";
$day['es'][2] = "Marzo";
$day['es'][3] = "Abril";
$day['es'][4] = "Mayo";
$day['es'][5] = "Junio";
$day['es'][6] = "Julio";
$day['es'][7] = "Agosto";
$day['es'][8] = "Septiembre";
$day['es'][9] = "Octubre";
$day['es'][10] = "Noviembre";
$day['es'][11] = "Diciembre";
/* ... */
$day['cat'][0] = "Gener";
$day['cat'][1] = "Febrer";
$day['cat'][2] = "Març";
$day['cat'][3] = "Abril";
$day['cat'][4] = "Maig";
$day['cat'][5] = "Juny";
$day['cat'][6] = "Juliol";
$day['cat'][7] = "Agost";
$day['cat'][8] = "Setembre";
$day['cat'][9] = "Octubre";
$day['cat'][10] = "Novembre";
$day['cat'][11] = "Desembre";
?>
