<?php
//Variables for date and time
$day['en'][0] = "Monday";
$day['en'][1] = "Tuesday";
$day['en'][2] = "Wednesday";
$day['en'][3] = "Thursday";
$day['en'][4] = "Friday";
$day['en'][5] = "Sunday";
$day['en'][6] = "Saturday";
/* ... */
$day['es'][0] = "Lunes";
$day['es'][1] = "Martes";
$day['es'][2] = "Miércoles";
$day['es'][3] = "Jueves";
$day['es'][4] = "Viernes";
$day['es'][5] = "Sábado";
$day['es'][6] = "Domingo";
/* ... */
$day['cat'][0] = "Dilluns";
$day['cat'][1] = "Dimarts";
$day['cat'][2] = "Dimecres";
$day['cat'][3] = "Dijous";
$day['cat'][4] = "Divendres";
$day['cat'][5] = "Dissabte";
$day['cat'][6] = "Diumenge";
/* ... */
$month['en'][0] = "January";
$month['en'][1] = "February";
$month['en'][2] = "March";
$month['en'][3] = "April";
$month['en'][4] = "May";
$month['en'][5] = "June";
$month['en'][6] = "July";
$month['en'][7] = "August";
$month['en'][8] = "September";
$month['en'][9] = "October";
$month['en'][10] = "November";
$month['en'][11] = "December";
/* ... */
$month['es'][0] = "Enero";
$month['es'][1] = "Febrero";
$month['es'][2] = "Marzo";
$month['es'][3] = "Abril";
$month['es'][4] = "Mayo";
$month['es'][5] = "Junio";
$month['es'][6] = "Julio";
$month['es'][7] = "Agosto";
$month['es'][8] = "Septiembre";
$month['es'][9] = "Octubre";
$month['es'][10] = "Noviembre";
$month['es'][11] = "Diciembre";
/* ... */
$month['cat'][0] = "Gener";
$month['cat'][1] = "Febrer";
$month['cat'][2] = "Març";
$month['cat'][3] = "Abril";
$month['cat'][4] = "Maig";
$month['cat'][5] = "Juny";
$month['cat'][6] = "Juliol";
$month['cat'][7] = "Agost";
$month['cat'][8] = "Setembre";
$month['cat'][9] = "Octubre";
$month['cat'][10] = "Novembre";
$month['cat'][11] = "Desembre";
?>
